//! AI Integration for Context Management
//!
//! Provides AI-powered features using tokitai-context's AIContext wrapper.
//! Requires LLM client implementation.

#[cfg(feature = "ai")]
use crate::error::CadAgentError;
use crate::error::CadAgentResult;
use serde::{Deserialize, Serialize};
#[cfg(feature = "ai")]
use tokitai_context::ai::client::LLMClient;
#[cfg(feature = "ai")]
use tokitai_context::facade::AIContext;
#[cfg(feature = "ai")]
use tokitai_context::parallel::ParallelContextManager;
#[cfg(feature = "ai")]
use tokitai_context::Context;

/// Branch purpose inferred by AI
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchPurpose {
    /// Inferred purpose description
    pub description: String,
    /// Confidence score (0.0-1.0)
    pub confidence: f32,
    /// Suggested merge strategy
    pub suggested_merge: String,
}

/// Merge recommendation from AI
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MergeRecommendation {
    /// Recommended action
    pub action: String,
    /// Risk level (Low/Medium/High)
    pub risk_level: String,
    /// Reasoning for the recommendation
    pub reasoning: Vec<String>,
    /// Suggested merge strategy
    pub suggested_strategy: String,
}

/// Branch summary generated by AI
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchSummary {
    /// Branch name
    pub branch_name: String,
    /// Summary text
    pub summary: String,
    /// Key decisions made in this branch
    pub key_decisions: Vec<String>,
    /// Number of turns in branch
    pub turn_count: usize,
}

/// Conflict resolution result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConflictResolution {
    /// Resolution description
    pub resolution: String,
    /// Conflicts resolved
    pub conflicts_resolved: usize,
    /// Remaining conflicts
    pub remaining_conflicts: usize,
}

/// AI Integration Manager
///
/// Provides AI-powered features:
/// - Branch purpose inference
/// - Merge recommendations
/// - Branch summarization
/// - Conflict resolution
///
/// # Feature Flag
///
/// Requires `ai` feature to be enabled.
pub struct AIIntegration {
    /// Current branch
    current_branch: String,
    /// LLM client (required for AI features)
    #[cfg(feature = "ai")]
    llm_client: Option<std::sync::Arc<dyn LLMClient>>,
}

impl AIIntegration {
    /// Create a new AIIntegration manager
    pub fn new(_session_id: &str, _context_root: &str) -> CadAgentResult<Self> {
        Ok(Self {
            current_branch: "main".to_string(),
            #[cfg(feature = "ai")]
            llm_client: None,
        })
    }

    /// Set the LLM client
    #[cfg(feature = "ai")]
    pub fn set_llm_client(&mut self, client: std::sync::Arc<dyn LLMClient>) {
        self.llm_client = Some(client);
    }

    /// Check if AI features are available
    #[cfg(feature = "ai")]
    pub fn is_ai_available(&self) -> bool {
        self.llm_client.is_some()
    }

    /// Check if AI features are available (stub for non-AI build)
    #[cfg(not(feature = "ai"))]
    pub fn is_ai_available(&self) -> bool {
        false
    }

    /// Infer branch purpose using AI
    ///
    /// # Arguments
    ///
    /// * `branch_name` - Name of the branch to analyze
    ///
    /// # Errors
    ///
    /// Returns error if AI is not available or inference fails
    #[cfg(feature = "ai")]
    pub async fn infer_branch_purpose(
        &self,
        branch_name: &str,
        ctx: &Context,
    ) -> CadAgentResult<BranchPurpose> {
        let client = self
            .llm_client
            .as_ref()
            .ok_or_else(|| CadAgentError::internal("LLM client not configured"))?;

        // Create AI context wrapper
        let ai_ctx = AIContext::new(ctx, client)
            .map_err(|e| CadAgentError::internal(format!("Failed to create AI context: {}", e)))?;

        // Infer purpose
        let purpose = ai_ctx
            .infer_branch_purpose(branch_name)
            .await
            .map_err(|e| CadAgentError::internal(format!("AI inference failed: {}", e)))?;

        Ok(BranchPurpose {
            description: purpose.description,
            confidence: purpose.confidence,
            suggested_merge: purpose.suggested_merge,
        })
    }

    /// Get merge recommendation from AI
    ///
    /// # Arguments
    ///
    /// * `source_branch` - Source branch to merge from
    ///
    /// # Errors
    ///
    /// Returns error if AI is not available or recommendation fails
    #[cfg(feature = "ai")]
    pub async fn get_merge_recommendation(
        &self,
        source_branch: &str,
        ctx: &Context,
    ) -> CadAgentResult<MergeRecommendation> {
        let client = self
            .llm_client
            .as_ref()
            .ok_or_else(|| CadAgentError::internal("LLM client not configured"))?;

        let ai_ctx = AIContext::new(ctx, client)
            .map_err(|e| CadAgentError::internal(format!("Failed to create AI context: {}", e)))?;

        let recommendation = ai_ctx
            .get_merge_recommendation(source_branch, &self.current_branch)
            .await
            .map_err(|e| CadAgentError::internal(format!("AI recommendation failed: {}", e)))?;

        Ok(MergeRecommendation {
            action: recommendation.action,
            risk_level: recommendation.risk_level,
            reasoning: recommendation.reasoning,
            suggested_strategy: recommendation.suggested_strategy,
        })
    }

    /// Summarize branch using AI
    ///
    /// # Arguments
    ///
    /// * `branch_name` - Name of the branch to summarize
    ///
    /// # Errors
    ///
    /// Returns error if AI is not available or summarization fails
    #[cfg(feature = "ai")]
    pub async fn summarize_branch(
        &self,
        branch_name: &str,
        ctx: &Context,
    ) -> CadAgentResult<BranchSummary> {
        let client = self
            .llm_client
            .as_ref()
            .ok_or_else(|| CadAgentError::internal("LLM client not configured"))?;

        let ai_ctx = AIContext::new(ctx, client)
            .map_err(|e| CadAgentError::internal(format!("Failed to create AI context: {}", e)))?;

        let summary = ai_ctx
            .summarize_branch(branch_name)
            .await
            .map_err(|e| CadAgentError::internal(format!("AI summarization failed: {}", e)))?;

        Ok(BranchSummary {
            branch_name: summary.branch_name,
            summary: summary.summary,
            key_decisions: summary.key_decisions,
            turn_count: summary.turn_count,
        })
    }

    /// Resolve conflicts using AI
    ///
    /// # Arguments
    ///
    /// * `source_branch` - Source branch with conflicts
    /// * `target_branch` - Target branch with conflicts
    /// * `conflict_description` - Description of the conflicts
    ///
    /// # Errors
    ///
    /// Returns error if AI is not available or resolution fails
    #[cfg(feature = "ai")]
    pub async fn resolve_conflict(
        &mut self,
        source_branch: &str,
        target_branch: &str,
        conflict_description: &str,
        ctx: &Context,
    ) -> CadAgentResult<ConflictResolution> {
        let client = self
            .llm_client
            .as_ref()
            .ok_or_else(|| CadAgentError::internal("LLM client not configured"))?;

        let ai_ctx = AIContext::new(ctx, client)
            .map_err(|e| CadAgentError::internal(format!("Failed to create AI context: {}", e)))?;

        let resolution = ai_ctx
            .resolve_conflict(source_branch, target_branch, conflict_description)
            .await
            .map_err(|e| {
                CadAgentError::internal(format!("AI conflict resolution failed: {}", e))
            })?;

        Ok(ConflictResolution {
            resolution: resolution.description,
            conflicts_resolved: resolution.conflicts_resolved,
            remaining_conflicts: resolution.remaining_conflicts,
        })
    }

    /// Perform AI-assisted merge with recommendation
    ///
    /// # Arguments
    ///
    /// * `source_branch` - Source branch to merge
    /// * `manager` - Parallel context manager for performing the merge
    ///
    /// # Errors
    ///
    /// Returns error if AI is not available or merge fails
    #[cfg(feature = "ai")]
    pub async fn ai_merge_with_recommendation(
        &mut self,
        source_branch: &str,
        manager: &ParallelContextManager,
    ) -> CadAgentResult<MergeRecommendation> {
        // Get recommendation first (needs ctx - we'll need to pass it)
        // For now, return error - this method needs refactoring
        Err(CadAgentError::internal(
            "ai_merge_with_recommendation requires Context parameter",
        ))
    }

    /// Get current branch
    pub fn current_branch(&self) -> &str {
        &self.current_branch
    }

    /// Set current branch
    pub fn set_current_branch(&mut self, branch: &str) {
        self.current_branch = branch.to_string();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_ai_integration_creation() {
        let temp_dir = tempdir().unwrap();
        let manager = AIIntegration::new("test-ai", temp_dir.path().to_str().unwrap()).unwrap();

        assert_eq!(manager.current_branch(), "main");

        // AI should not be available without client
        assert!(!manager.is_ai_available());
    }

    #[test]
    #[cfg(feature = "ai")]
    fn test_ai_not_available_without_client() {
        let temp_dir = tempdir().unwrap();
        let mut manager =
            AIIntegration::new("test-ai-no-client", temp_dir.path().to_str().unwrap()).unwrap();

        // Without setting client, AI should not be available
        assert!(!manager.is_ai_available());
    }
}
